volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8787:8787"
      - "5555:5555"
    entrypoint:
      - /usr/bin/tini
      - --
    command: pnpm dev
    depends_on:
      - db
  db:
    image: postgres:17.1-bookworm
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
